#!/usr/bin/env bash
# Generate wifi_credentials.generated.h from secrets/wifi.yaml
#
#   ./scripts/gen-wifi-credentials.sh
#   ./scripts/gen-wifi-credentials.sh path/to/wifi.yaml
#
# Output (gitignored):
#   esp32_firmware/apps/wifi_connect/main/wifi_credentials.generated.h
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
YAML="${1:-$REPO/secrets/wifi.yaml}"
OUT_DIR="$REPO/esp32_firmware/apps/wifi_connect/main"
OUT="$OUT_DIR/wifi_credentials.generated.h"
EXAMPLE="$REPO/secrets/wifi.yaml.example"

if [[ ! -f "$YAML" ]]; then
  echo "error: missing $YAML" >&2
  echo "  cp secrets/wifi.yaml.example secrets/wifi.yaml  # then edit passwords" >&2
  exit 1
fi

if [[ ! -d "$OUT_DIR" ]]; then
  echo "error: wifi_connect app not found at $OUT_DIR" >&2
  exit 1
fi

# Parse simple YAML list:
# ---
# - ssid: Name
#   password: "secret"
# Uses Python stdlib only (no PyYAML required).
python3 - "$YAML" "$OUT" <<'PY'
import re, sys
from pathlib import Path

yaml_path, out_path = Path(sys.argv[1]), Path(sys.argv[2])
text = yaml_path.read_text(encoding="utf-8")

# Strip comments
lines = []
for line in text.splitlines():
    if re.match(r"^\s*#", line):
        continue
    lines.append(line)
text = "\n".join(lines)

entries = []
cur = {}
for line in text.splitlines():
    m = re.match(r"^\s*-\s*ssid:\s*(.*)$", line)
    if m:
        if cur.get("ssid"):
            entries.append(cur)
        cur = {"ssid": m.group(1).strip().strip("\"'"), "password": ""}
        continue
    m = re.match(r"^\s*password:\s*(.*)$", line)
    if m and cur:
        raw = m.group(1).strip()
        if (raw.startswith('"') and raw.endswith('"')) or (
            raw.startswith("'") and raw.endswith("'")
        ):
            raw = raw[1:-1]
        cur["password"] = raw
if cur.get("ssid"):
    entries.append(cur)

# Drop empty / example placeholders if password still change-me? keep them — user responsibility

def c_string(s: str) -> str:
    return (
        '"'
        + s.replace("\\", "\\\\").replace('"', '\\"')
        + '"'
    )

out = []
out.append("/* AUTO-GENERATED by scripts/gen-wifi-credentials.sh — DO NOT COMMIT */")
out.append("#pragma once")
out.append("#include <stddef.h>")
out.append("")
out.append("typedef struct {")
out.append("    const char *ssid;")
out.append("    const char *password;")
out.append("} wifi_known_network_t;")
out.append("")
out.append(f"#define WIFI_KNOWN_NETWORK_COUNT {len(entries)}")
out.append("")
if entries:
    out.append("static const wifi_known_network_t WIFI_KNOWN_NETWORKS[] = {")
    for e in entries:
        out.append(
            f"    {{ .ssid = {c_string(e['ssid'])}, .password = {c_string(e.get('password') or '')} }},"
        )
    out.append("};")
else:
    out.append("/* No networks in secrets file */")
    out.append("static const wifi_known_network_t WIFI_KNOWN_NETWORKS[] = {")
    out.append("};")

out_path.write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"Wrote {len(entries)} network(s) -> {out_path}")
for e in entries:
    print(f"  - {e['ssid']}")
PY
